In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from pandas import DataFrame

url ="https://www.psx.com.pk/market-summary/"

ss = requests.get(url)
obj = BeautifulSoup(ss.content,'lxml')
# obj.text

In [2]:
data = obj.findAll("div",{"class":"table-responsive"})

In [3]:
# for link in data:
titles = data[0].get('h4')
print(titles)

None

In [4]:
title = obj.find_all('th')
# tables[4].text
titles = []
for i in range(4,38):
    titles.append(title[i].text)

# print(titles[2])
# dataframe = pd.DataFrame(titles)

# print(dataframe)
# col1 = tables[5].text
# col2 = tables[6].text
# col3 = tables[7].text

# for table in tables:
#     print(table.text)

In [5]:
rows = obj.find_all('td')
row_data = []
for i in range(30,len(rows)):
    row_data.append(rows[i].text)
#     print(row_data[i])
    
# print(len(row_data),row_data[3167])
row1 = row_data[8:16:1]
# print(row1[0])
cols = row_data[0:8:1]
row2 = row_data[16:24:1]
row3 = row_data[24:32:1]
# row4 = row_data[32:40:1]
# print(row_data[0])

j = 4   #row nUm
k = 32   #slicing start index
l = 40    #slicing end index
# m =
row4 = []
for i in range(k,len(row_data)):
    
    k =l
    l=l+8
    row4.append(row_data[k:l:1])

# for i in row4:
# # print(row4.index('SCRIP'))
# for i in row4:
#     print(i)
#     if(i != "SCRIP"):
#         print(i)
        


#         print(i)
        
        
        
        
    
#     print(row4)
    
# print(row4)

# str('abc') +""+ str(5) = 67
# j+=1    
# cols[7]
# print(row3)

from pandas import Series
import csv

# with open('employee_birthday.csv','w') as csv_file:
#     spamwriter = csv.writer(csv_file)
#     spamwriter.writerow(cols)
#     spamwriter.writerow(row1)
    
# csv_file.close()
with open('Stocks.csv','a') as csv_file:
    spamwriter = csv.writer(csv_file)
    spamwriter.writerow(row1)
    spamwriter.writerow(row2)
    spamwriter.writerow(row3)
    spamwriter.writerows(row4)
# # csv_file.close()    
# # with open('employee_birthday.csv') as csv_file:
# #     reader = csv.DictReader(csv_file)    
# df = pd.DataFrame()
# df = pd.read_csv('employee_birthday.csv')
# df.head()

# col = pd.Series([],col)
# print(d)

# for i in range(len(row4)):
    
# #     print(row4[i][0])
#     if(row4[i][0]=="SCRIP"):
#         del row4[i][0]
        
#     else:
#         continue
        
# #         row4.remove(i)
# for i in row4:
#     print(i)

In [93]:
print(data[1])

<div class="table-responsive">
<table>
<thead>
<tr>
<th colspan="8"><h4> AUTOMOBILE ASSEMBLER</h4></th>
</tr>
</thead>
<tr>
<td>SCRIP</td>
<td>LDCP</td>
<td>OPEN</td>
<td>HIGH</td>
<td>LOW</td>
<td>CURRENT</td>
<td>CHANGE</td>
<td>VOLUME</td>
</tr>
<tr class="green-text-td">
<td>Al-Ghazi Tractors Limited. </td>
<td>275.96</td>
<td>275.00</td>
<td>281</td>
<td>273.5</td>
<td>279.68</td>
<td> <span class="increase-rate"></span> 3.72</td>
<td>12,200</td>
</tr>
<tr class="green-text-td">
<td>Atlas Honda Limited. </td>
<td>298.01</td>
<td>300.00</td>
<td>305</td>
<td>295</td>
<td>305</td>
<td> <span class="increase-rate"></span> 6.99</td>
<td>7,500</td>
</tr>
<tr class="red-text-td">
<td>Dewan Farooque Motors Limited [ DEFAULTER SEGMENT ]</td>
<td>5.78</td>
<td>5.65</td>
<td>5.79</td>
<td>5.51</td>
<td>5.61</td>
<td> <span class="decrease-rate"></span> -.17</td>
<td>45,500</td>
</tr>
<tr class="red-text-td">
<td>Ghandhara Industries Ltd. </td>
<td>76.26</td>
<td>75.32</td>
<td>77.1</td>
<td>74.76</td>
<td>75.31</td>
<td> <span class="decrease-rate"></span> -.95</td>
<td>134,500</td>
</tr>
<tr class="red-text-td">
<td>Ghandhara Nissan Ltd. </td>
<td>48.58</td>
<td>48.60</td>
<td>49.39</td>
<td>48</td>
<td>48.28</td>
<td> <span class="decrease-rate"></span> -.3</td>
<td>58,500</td>
</tr>
<tr class="red-text-td">
<td>Ghani Automobile Industries Ltd. </td>
<td>3.75</td>
<td>3.75</td>
<td>3.84</td>
<td>3.71</td>
<td>3.74</td>
<td> <span class="decrease-rate"></span> -.01</td>
<td>16,500</td>
</tr>
<tr class="red-text-td">
<td>Hino Pak Motor Limeted. </td>
<td>290.00</td>
<td>290.00</td>
<td>290</td>
<td>281.5</td>
<td>281.75</td>
<td> <span class="decrease-rate"></span> -8.25</td>
<td>600</td>
</tr>
<tr class="red-text-td">
<td>Honda Atlas Cars (Pak) Ltd. </td>
<td>136.10</td>
<td>136.25</td>
<td>138</td>
<td>134.5</td>
<td>135.71</td>
<td> <span class="decrease-rate"></span> -.39</td>
<td>62,400</td>
</tr>
<tr class="red-text-td">
<td>Indus Motor Company Ltd.(XD) </td>
<td>980.24</td>
<td>971.00</td>
<td>971</td>
<td>940.01</td>
<td>940.08</td>
<td> <span class="decrease-rate"></span> -40.16</td>
<td>3,880</td>
</tr>
<tr class="red-text-td">
<td>Millat Tractors Limited.(XDXB) </td>
<td>625.63</td>
<td>630.94</td>
<td>630.99</td>
<td>622</td>
<td>623.50</td>
<td> <span class="decrease-rate"></span> -2.13</td>
<td>7,300</td>
</tr>
<tr class="red-text-td">
<td>Pak Suzuki Motors Co Ltd. </td>
<td>161.01</td>
<td>160.01</td>
<td>164.98</td>
<td>156.5</td>
<td>160.18</td>
<td> <span class="decrease-rate"></span> -.83</td>
<td>18,200</td>
</tr>
</table>
</div>

In [79]:
# data1[400]